### ISSUE TITLE
An intermittent should not be considered a regression if it was already intermittent in one of its parents

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#1]
It's not perfectly clear, as maybe a new intermittent was introduced on the current push, but it might be better not to consider intermittently failing tasks that were already intermittently failing in one of the parents.

**Comment by ahal** [comment]
If we're going to go back a significant number of pushes, we might want to modify the AD query to fetch the `tasks` for many pushes at a time (rather than push by push) to save overhead.
