### ISSUE TITLE
Run integration tests on cron

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#134]
We stopped running them since #91 landed (the last build where we run them was https://travis-ci.org/github/mozilla/mozci/builds/663523324, the first where we didn't was https://travis-ci.org/github/mozilla/mozci/builds/663967977).

**Comment by ahal** [comment]
Sorry, should have verified it was working after landing. I don't immediately see why it's not though, according to [this](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables) we are skipping the tests on the right variable here:
https://github.com/mozilla/mozci/blob/master/tests/test_integration.py#L11

**Comment by ahal** [comment]
Oh, this is because I didn't add the `passenv` key to tox.
