### ISSUE TITLE
Point kyle to group-scheduled artifact

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/mozci#136]
Used as a reference to build dashboard

**Comment by ahal** [comment]
@klahnakoski could you expand on what you need here?

No tasks are currently scheduled by group, and likely won't be for several months to come. Here is a test artifact that contains group information:
https://firefoxci.taskcluster-artifacts.net/dSO77clkT5KF2IUh-NoDqw/0/public/test_info//mochitest-browser-chrome_raw.log

(see the `suite_start` log action and related tests dict)

Though this is just what AD has been consuming for years, so I assume it's not what you're looking for. Assuming what you're looking for doesn't exist yet, maybe we can close this issue.

**Comment by klahnakoski** [comment]
@ahal I thought this was going to happen sooner, so I made this issue as a reminder.
