### ISSUE TITLE
Formalize and implement "data sources"

### ISSUE THREAD

**Issue by ahal** [mozilla/mozci#139]
Cam would like to start using mozci to determine whether a push has a regression or not (see https://github.com/mozilla/treeherder/issues/6220).

The problem is that he needs to query some of his data from Treeherder because ActiveData isn't current enough to work on brand new pushes. There are certain scenarios where Cam may still want to use AD though.

When thinking about how best to solve this, I came up with the concept of a "data source". The idea is that ``mozci`` doesn't really care where it gets its data from, just that it is accurate. So we could have a set of sources (Treeherder, ActiveData, Cache(s), Taskcluster artifacts, etc) and if mozci fails to gather data from one source, it could try it from another as a fallback. We already do this to an extent.. First we check the local cache, if that fails we run an ActiveData query, if that fails we fill in data using artifacts. So this proposal is more about formalizing a practice we already do and then implementing additional data sources.

A few misc notes:
* We could make which data sources are enabled configurable, and even allow users to prioritize which ones should be queried first (e.g, treeherder and then AD or vice versa).

* Not all data sources will be able to fulfill all data needs. So we'll need some way for sources to "register" which requests they are capable of fulfilling.

* Getting treeherder to use mozci will block path-scheduling

As far as the concrete implementation goes there are a few approaches we could take:

1. Implement this within mozci
2. Implement this as a new generic query all the things repo that mozci depends on
3. Morph ``adr`` into the above

This also has implications on mozci's relationship to adr. We can:

a. Remove ``adr`` as a dependency and implement a new (much simpler) ActiveData source
b. Continue using ``adr`` as the ActiveData source

Initially I think I'm leaning towards 1-b.

**Comment by marco-c** [comment]
> Getting treeherder to use mozci will block path-scheduling

Out of curiosity, why?

> Initially I think I'm leaning towards 1-b.

I agree, I like the idea overall. I think it also makes building tests easier (as you can create a "fake" data source).

I see two possible architectures for 1b:
- the user of the library instantiates data source classes, generates the data using those classes in a format that the Push class understands, then instantiates the Push class with the data as input;
- the user of the library instantiates a Push class, the Push class has the responsibility of instantiating the data source classes and generating data using those classes (the user of the library can define what data source classes the Push class should use).

The data source classes can be either the ones built-in in mozci, or the user can define new ones.

**Comment by ahal** [comment]
> > Getting treeherder to use mozci will block path-scheduling
> 
> Out of curiosity, why?

Because Push Health uses simple heuristics to try and guess at regressions. Namely looking at the task label on the parent push to see if it also failed there. With test path scheduling, that heuristic will be invalid. Since `mozci` already solves this with "group" regressions, and since it is much more sophisticated, it makes the most sense to get Push Health to use it.

Note, I think this work should likely be a high priority because:
1. It blocks test path scheduling in the long term
2. It has immediate benefit to Push Health in the short term (more accurate regression detection)

**Comment by klahnakoski** [comment]
We may want to consider changing the ActiveData-ETL pipeline from a batch-based to stream based:  https://github.com/klahnakoski/ActiveData-ETL/issues/77

**Comment by marco-c** [comment]
Fixed by #241.
