### ISSUE TITLE
Bug 1622336 - Query the 'bugbug' schedules service as early as possible

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozci#140]
https://bugzilla.mozilla.org/show_bug.cgi?id=1622336

**Comment by ahal** [comment]
Fyi if you added this to get it into the project, you can alternatively create a "Note" and link the bug from that. That way we don't pollute the repos with unrelated issues, you can see some examples I've already created.

**Comment by armenzg** [comment]
I've done so:
https://github.com/orgs/mozilla/projects/121#card-35914836
<img width="262" alt="image" src="https://user-images.githubusercontent.com/44410/78715322-3defe100-78eb-11ea-8803-43b720d5495f.png">

Closing!
