### ISSUE TITLE
Push.generate_all_shadow_scheduler_tasks() shouldn't fall over if any given shadow-scheduler fails

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/mozci#144]
`generate_all_shadow_scheduler_tasks()` is a generator that relies on `get_shadow_scheduler_tasks()` which appears to throw exceptions:  If any one scheduler messed up, collecting the others fail.  I suggest coding this function/generator so it provides as much information as possible; returning `None` for missing data or any other problems.  

If you do code in this none-safe way:  Consider shunting all exceptions to the logging channel as "warnings"; where "warning" is defined as an error that has a (non-optimal) mitigation.

**Comment by ahal** [comment]
Yes you're right, good catch!
