### ISSUE TITLE
Add a way to make a task JSON serializable

### ISSUE THREAD

**Issue by camd** [mozilla/mozci#146]
This would facilitate returning `tasks` from a REST endpoint.  Push Health could use this.

**Comment by ahal** [comment]
This would definitely be solvable on the `PushHealth` side by creatin a specialized `JSONEncoder` like this:
https://stackoverflow.com/a/3768975

However, I see no harm in implementing a `to_json()` method on this class. Could come in useful in other places as well.

**Comment by camd** [comment]
Cool, yeah, either of those would be great.  The `to_json()` function sounds like an easy way to handle this.  Perhaps I need to start submitting PRs, though, too.  :)
