### ISSUE TITLE
Get bugs fixed by changesets directly from the ActiveData repo table

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#155]
Currently we hit hgmo to get this info.

Depends on https://github.com/mozilla/ActiveData/issues/196.

**Comment by marco-c** [comment]
This would help with https://github.com/mozilla/bugbug/issues/1449.

**Comment by jmaher** [comment]
@marco-c I assume we can close this out given that AD doesn't exist anymore?

**Comment by marco-c** [comment]
Definitely.
