### ISSUE TITLE
Make WPT return full relative paths and adjust `is_bad_group` check

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#161]
Currently, with 61720ebc59424a955458ad2be43560b2e4401ddd, we have a special case for WPT tasks (https://github.com/mozilla/mozci/blob/11777df4ad7b8d21922c37b8a51c80b5f1fc690f/mozci/task.py#L50-L55).

We should check if the harness could return full relative paths, so we have the same behavior as the other suites.

**Comment by marco-c** [comment]
@ahal did you figure this out?

**Comment by marco-c** [comment]
> No, haven't had time. Is there a translation in mozci already? If not, can we add one? Or is fixing this in WPT on the critical path?

No there's nothing yet in mozci, I don't know if we can add one: I'm not sure if those paths are *always* relative to testing/web-platform/tests/. If they are, then yeah, we could add a translation in mozci in the meantime.

**Comment by ahal** [comment]
They are either relative to there or relative to
`testing/web-platform/mozilla/tests`. There are examples of detecting which
one it is in-tree, Edwin recently had to do this.

**Comment by worldomonation** [comment]
Note I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1632546 for this. 

Please feel free to correct my statements if they are not accurate.

**Comment by marco-c** [comment]
I thought I could use a workaround in bugbug and just check if the path existed in `testing/web-platform/mozilla/tests` or `testing/web-platform/tests`, but @worldomonation told me some paths could be in both directories, so we have no way to apply this workaround.
Also, in mozci we'd have the same group name for two sets of tests which are actually different, with the clear consequences.

**Comment by marco-c** [comment]
@ahal noticed that groups from `testing/web-platform/mozilla/tests` start with `/_mozilla/`, so we can use the presence of that prefix to detect to which directory the group belongs to.
