### ISSUE TITLE
Make sure we don't try to load errorsummary.log for suites which don't support it

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#186]

**Comment by marco-c** [comment]
Actually, we are already doing this.

**Comment by marco-c** [comment]
I'll just add an assertion to make sure we don't regress.

**Comment by armenzg** [comment]
For the curious, it was discovered that `jittests` and `marionette` tasks were being fetched for their error summaries:
https://gist.github.com/armenzg/e4fa3ae6a572224385427a4b7da54080
