### ISSUE TITLE
Use 'fixed by commit' and back-out information to correctly attribute some regressions

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#2]
For example, test-macosx1014-64-shippable/opt-mochitest-devtools-chrome-e10s-1 is failing in https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=ec8cad6891215a6db48cf2bc927ef6c77838035f.

The failure was marked by sheriffs as fixed by commit [6777cec97d18](https://hg.mozilla.org/integration/autoland/rev/69a232cb693503d98c04ddc5acace1d930bf4898), which is a backout of 31a1b40b20084e96947cf3b660a5b5ef9c5612d0.

test-macosx1014-64-shippable/opt-mochitest-devtools-chrome-e10s-1 did run on 31a1b40b20084e96947cf3b660a5b5ef9c5612d0, and it was successful.

**Comment by ahal** [comment]
Yeah, I guess we need to look at history for these as well.. not just intermittents.

**Comment by marco-c** [comment]
In a case like this, since we have the hash of the commit which fixed the failure, and the commit which fixed the failure is a backout of another commit, we could attribute the failure to the commit which was backed out.

The situation is:
commit A
commit B causes test 1 to fail, the failure is marked as fixed by commit C
commit C backs-out A

Here we can consider test 1 to be a regression of commit A, and completely remove it from the likely or possible regressions of commit B.

I'm not sure how frequent this situation is though.
