### ISSUE TITLE
Remove code supporting the legacy Taskcluster deployment

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#230]
The legacy Taskcluster deployment is going to be decommissioned soon, we can remove any code to support it.

**Comment by satrio-hw** [comment]
hi @marco-c , can I take this issue to working on?

**Comment by marco-c** [comment]
Sure! You'll need to basically remove all the code related to `old_deployment` in mozci/util/taskcluster.py (more or less reverting the changes from a2bc168b98d79456d0ebc50192d49ef278fdc9ac).
