### ISSUE TITLE
On manifest-level pushes, consider regressions of labels which are not manifest-level

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#245]
#244 is OK as a temporary workaround while we run the manifest-level experiment.
In the longer term, if we want to make manifest-level the default, we need to ensure we can still find label-level regressions for tasks that do not have manifests (e.g. cppunit, gtest, build, reftest until it's manifest-level, etc.).

**Comment by marco-c** [comment]
We need a way to detect which tasks were generated by chunking in the taskgraph.
We could use the presence of MOZHARNESS_TEST_PATHS in the env (@ahal can you confirm?).

The tasks' env is not available in the unittest or treeherder tables, so we'd need to query a third table, `task`.

`task.env` from the results of `{"from":"task","select":["task.id","task.env"]}` is a list of dicts such as `{"name":"SCCACHE_DISABLE","value":"1"}`.

@klahnakoski is there a way to make a query that returns all the task IDs for tasks that have MOZHANESS_TEST_PATHS in the list of envs?
Would it be better to avoid a third query and store this data (whether MOZHANESS_TEST_PATHS is in the env or not) in AD either in the treeherder table (under run.taskcluster) or in the unittest table (under task)?

**Comment by armenzg** [comment]
By the end of the month, I will have information on the Treeherder tables about manifests that a task is scheduled to execute (via MOZHARNESS_TEST_PATHS).
In case it helps.

**Comment by marco-c** [comment]
> By the end of the month, I will have information on the Treeherder tables about manifests that a task is scheduled to execute (via MOZHARNESS_TEST_PATHS).
In case it helps.

I don't need to know which manifests a task scheduled (I already have that info from AD or from errorsummary.log), but I need to know which tasks are "old-style" tasks and which tasks are resulting from manifest-scheduling.

**Comment by armenzg** [comment]
The pressence of`MOZHARNESS_TEST_PATHS` is what differentiates them.

**Comment by marco-c** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1657192 is adding a tag for this to tasks.
