### ISSUE TITLE
Calling get_likely_regressions returns error voluptuous.error.MultipleInvalid: not a valid value for dictionary value @ data[1430]['classification']

### ISSUE THREAD

**Issue by ahal** [mozilla/mozci#266]
From Cam:

```
This is with latest master on mozci:

backend | [2020-09-01 23:26:10,751] ERROR [django.request:228] Internal Server Error: /api/project/try/push/health_ci/
backend | Traceback (most recent call last):
backend | File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
backend | response = get_response(request)
backend | File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
backend | response = self.process_exception_by_middleware(e, request)
backend | File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
backend | response = wrapped_callback(request, *callback_args, **callback_kwargs)
backend | File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
backend | return view_func(*args, **kwargs)
backend | File "/usr/local/lib/python3.7/site-packages/rest_framework/viewsets.py", line 114, in view
backend | return self.dispatch(request, *args, **kwargs)
backend | File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
backend | response = self.handle_exception(exc)
backend | File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
backend | self.raise_uncaught_exception(exc)
backend | File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
backend | raise exc
backend | File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
backend | response = handler(request, *args, **kwargs)
backend | File "/app/treeherder/webapp/api/push.py", line 267, in health_ci
backend | likely_regression_labels = mozciPush.get_likely_regressions('label')
backend | File "/mozci/mozci/push.py", line 934, in get_likely_regressions
backend | for name, count in self.get_regressions(runnable_type).items()
backend | File "/usr/local/lib/python3.7/site-packages/adr/util/memoize.py", line 27, in method_call
backend | cache[(args, kwargs_tuple)] = self.func(instance, *args, **kwargs)
backend | File "/mozci/mozci/push.py", line 877, in get_regressions
backend | runnable_summaries = getattr(other, f"{runnable_type}_summaries")
backend | File "/usr/local/lib/python3.7/site-packages/adr/util/memoize.py", line 46, in get
backend | setattr(instance, name, self.func(instance))
backend | File "/mozci/mozci/push.py", line 459, in label_summaries
backend | for task in self.tasks:
backend | File "/usr/local/lib/python3.7/site-packages/adr/util/memoize.py", line 46, in get
backend | setattr(instance, name, self.func(instance))
backend | File "/mozci/mozci/push.py", line 250, in tasks
backend | tasks = data.handler.get("push_tasks", branch=self.branch, rev=self.rev)
backend | File "/mozci/mozci/data/base.py", line 70, in get
backend | contract.validate_out(result)
backend | File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in call
backend | return self._compiled([], data)
backend | File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 635, in validate_sequence
backend | cval = validate(index_path, value)
backend | File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
backend | return base_validate(path, iteritems(data), out)
backend | File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
backend | raise er.MultipleInvalid(errors)
backend | voluptuous.error.MultipleInvalid: not a valid value for dictionary value @ data[1430]['classification']

I think this happens with most/all revisions. But I hit this on try with revision c076a08595452957f6084a8491ce94251dad35e8
```

**Comment by ahal** [comment]
Confirming that I can reproduce.

STR:
```
from mozci.push import Push
push = Push("c076a08595452957f6084a8491ce94251dad35e8", branch="try")
push.get_likely_regressions("label")
```

Calling `push.get_likely_regressions("group")` also fails, but for a different reason. It hits this assertion:
https://github.com/mozilla/mozci/blob/master/mozci/task.py#L404

**Comment by marco-c** [comment]
> Calling push.get_likely_regressions("group") also fails, but for a different reason. It hits this assertion:
https://github.com/mozilla/mozci/blob/678185ea9d4a673c78b4a71e3abcb58fd6b80123/mozci/task.py#L404

Interesting, that means a GroupSummary was created with at least one task that didn't contain the group itself.
It should never happen given how `GroupSummary`es are built: https://github.com/mozilla/mozci/blob/678185ea9d4a673c78b4a71e3abcb58fd6b80123/mozci/push.py#L424-L449

**Comment by marco-c** [comment]
> Calling push.get_likely_regressions("group") also fails, but for a different reason. It hits this assertion:
https://github.com/mozilla/mozci/blob/678185ea9d4a673c78b4a71e3abcb58fd6b80123/mozci/task.py#L404

Interesting, that means a GroupSummary was created with at least one task that didn't contain the group itself.
It should never happen given how `GroupSummary`es are built: https://github.com/mozilla/mozci/blob/678185ea9d4a673c78b4a71e3abcb58fd6b80123/mozci/push.py#L424-L449

**Comment by marco-c** [comment]
Sorry...

**Comment by marco-c** [comment]
I filed #267 for the assertion failure.

**Comment by camd** [comment]
With the fix above, I now get a slightly different error:

            |   File "/mozci/mozci/push.py", line 481, in label_summaries
            |     for task in self.tasks:
            |   File "/usr/local/lib/python3.7/site-packages/adr/util/memoize.py", line 46, in __get__
            |     setattr(instance, name, self.func(instance))
            |   File "/mozci/mozci/push.py", line 250, in tasks
            |     tasks = data.handler.get("push_tasks", branch=self.branch, rev=self.rev)
            |   File "/mozci/mozci/data/base.py", line 70, in get
            |     contract.validate_out(result)
            |   File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
            |     return self._compiled([], data)
            |   File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 635, in validate_sequence
            |     cval = validate(index_path, value)
            |   File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
            |     return base_validate(path, iteritems(data), out)
            |   File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
            |     raise er.MultipleInvalid(errors)
            | voluptuous.error.MultipleInvalid: expected str for dictionary value @ data[0]['id']

**Comment by camd** [comment]
fwiw: This is the url I tested locally: http://localhost:5000/api/project/try/push/health_ci/?revision=c076a08595452957f6084a8491ce94251dad35e8
