### ISSUE TITLE
push_revisions query is no longer working

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#28]
> WARNING  | adr.query:132 - Query 'push_revisions' returned no data with context: from_date=today-25day, to_date=today, branch=autoland, from_push=104645, to_push=106310

This is a regression from 589ae9fb4eaa4acb642b9e12c8803b9f59ac6574, as the following patch fixes the problem:
```
diff --git a/mozci/push.py b/mozci/push.py
index c824c58..ef845de 100644
--- a/mozci/push.py
+++ b/mozci/push.py
@@ -474,8 +480,7 @@ def make_push_objects(**kwargs):
 
         data += run_query("push_revisions", Namespace(**kwargs))["data"]
 
-    for row in data:
-        pushid, date, revs, parents = row['pushid'], row['date'], row['revs'], row['parents']
+    for pushid, date, revs, parents in data:
         topmost = list(set(revs) - set(parents))[0]
 
         cur = Push([topmost] + [r for r in revs if r != topmost])
diff --git a/mozci/queries/push_revisions.query b/mozci/queries/push_revisions.query
index 6b21fab..acf380d 100644
--- a/mozci/queries/push_revisions.query
+++ b/mozci/queries/push_revisions.query
@@ -12,16 +12,15 @@ where:
         - gte: [push.id, {$eval: from_push}]
         - lte: [push.id, {$eval: to_push}]
 limit: 100000
-format: list
-destination: url
+format: table
```

**Comment by marco-c** [comment]
Same with the treeherder query, e.g.:
> WARNING  | adr.query:132 - Query 'push_tasks_from_treeherder' returned no data with context: rev=432ef8822e876751a14eb96e1d3bdb94e80bbf23, branch=autoland

**Comment by marco-c** [comment]
@klahnakoski could you look into this?

**Comment by marco-c** [comment]
I think it's simply because ci-recipes was using an old version of adr, let me check...

**Comment by marco-c** [comment]
> I think it's simply because ci-recipes was using an old version of adr, let me check...

No, it looks like the result is the same even with a newer adr.

**Comment by marco-c** [comment]
I think the issue is the sort parameter in the query. It'd be nice if ADR/ActiveData printed an error when a query parameter is not supported.

**Comment by klahnakoski** [comment]
`format: table`  doe snot work with `destination: url`

**Comment by klahnakoski** [comment]
https://github.com/mozilla/ActiveData/blob/dev/docs/jx_big_data.md#some-important-notes

**Comment by marco-c** [comment]
> `format: table`  does not work with `destination: url`

We are using `format: list`
