### ISSUE TITLE
Wrong push head when walking parents from 5fce80b70b092ce127a800874831572faebe654a

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#288]
We are jumping from 5fce80b70b092ce127a800874831572faebe654a on try, to 7927a17052473b338d511c15bc940f862ee9e3e0 on mozilla-central (which is correct), to 81d47e62000723a24bb20f1abdda51cfc62c553f on autoland (which is wrong).

81d47e62000723a24bb20f1abdda51cfc62c553f is in the middle of a push, and not a push head.

Also, in theory, we should prefer mozilla-central to autoland (see https://github.com/mozilla/mozci/blob/d2079c5ec3802c3cd7a5c8160ad7e7d5ac1b9b99/mozci/push.py#L179-L181).

**Comment by ahal** [comment]
Notably, `81d4` *is* a push head on central:
https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&revision=81d47e62000723a24bb20f1abdda51cfc62c553f

So looks like it correctly found the parent push head on central, but then jumped to autoland for some reason. Likely also related is the fact that `81d4` is a merge commit which landed on `central` first, and was then pushed back up to `autoland` later. Maybe the algorithm is preferring the most recent push.

**Comment by ahal** [comment]
Turns out the mistake is dumber than all that. We never go down into that branch search due to:
https://github.com/mozilla/mozci/blob/d2079c5ec3802c3cd7a5c8160ad7e7d5ac1b9b99/mozci/push.py#L164

There's a bug in `create_push` where we don't pass in `self.branch`.
