### ISSUE TITLE
there are tasks found in group_durations query which are not found in pushes.tasks list

### ISSUE THREAD

**Issue by jmaher** [mozilla/mozci#297]
this is rare, but I keep finding instances where group_durations.query for a given time period returns results with a [valid] task_id and I am not able to find this by iterating through the pushes in the same time period and examining the tasks for that push.

**Comment by jmaher** [comment]
an example of tasks from september 16th:
['JtrAYIu9S1GBy8x_nFlheA', 'KP32gdGzTFOwF8aa7XSkaA', 'RkqI7oTFQlGUJBP1xQBIRA', 'SUjk-4YkQyyq540c4_93zA', 'VZvw_FxaTz6lt2MNQ8qOqg', 'bSgS6nefTEegVcs3QVRGZw', 'cCAy_in4R9qyEEThO1-4Gw', 'DyxLnlgzTq2LxKga4Q0Rcg', 'GsRMS3gGRvi4OohUi0_UNw', 'T_YP0pHqSmWCvv33mNZ6eQ', 'Y9nCGLt6QZWngYTJMLEswQ', 'YLxl_IunS4aqm76S2DOl9A', 'd5tl0iiKTZKLruK_MArLEQ', 'IKPZNPidQParPoZxbR2_fg', 'NidOrZC6Rre3hERaSZ71sg', 'IuuLHLiNRAaFSPsxIDSWMA', 'N9ebarB0Q--mXpDtEi28Ww', 'Bwz6DA-xRt-F9jZ_V6t7Qw', 'DzUjmhP7TFOlaFh0g9dpCA', 'Qj0N8lL3T_6mWf5GukpGHA', 'XTiEJYRfSM-W_9L3h_WBcA', 'Cc9jVq5tS_K1r-MJNIkJbQ', 'Y-R6Uva9TAS6a1HQAwPIMw', 'BLzSQmm-QS-KBTxtX3UH6Q', 'egrStvPxQQed-DQBiqN6vA', 'E8lSSn7HTXWhqEcilH8nvg', 'dHnITEciRGSh_eLJ2iG__Q', 'Rr60DiFMRw2DOWTLEjqO4A', 'YgERJA8nSZCDtWPPDcMwdA', 'It38ua-6RROXr1hAiDz_6g', 'SrJHSrsZSeaiskYDMyd5Ow', 'WDkUEEuURZ2Wzdd3GgZrGg', 'Xt7zIdNkT9Sl5nyqLl38oQ', 'EYVUJy1BSI-vRGYA33BrZQ', 'f1OJP8z4T8uMe4llK6GMZw', 'Bb9Dz3FOQVKyzqOwjcdILw', 'Z0py7vjGSYmKYaV4ATrPSw', 'PzgeIfGaQvyZxZ5n17g7sQ', 'O0sDC7I7SLmOSkeIICkIqg', 'LKCy-CNxTxWPbSz5tgBLow', 'eq8rb4YfQiagOX1jDTl3Kw', 'OokHWH5tRdOT2lqXtPBonQ', 'N8a1ujNnRGO-iP1GsUHZng', 'Z3euUHSvQNmjNuZUpbsXjw', 'U7AkJuckQo-gM0Nx5TB-ug', 'LQM6PJKBR1ODNm_8F2sTXg', 'SGBfjiiOS0OZRKTzYCNoCw', 'ABs39xyGScOANRSQBphyxg', 'OpgEgpghTtK3KCsARhYung', 'WEJPQkVfQzOJo1WK3aqyyA']

and some from sept 17th:
['AYbA40n6S5C_4q0uitzTCA', 'Ovv88lakSluDZesuP4Q0SQ', 'KH4fG9CSTdmZHOs7I9hUAQ', 'f1olC29kRAqf2cr32q5taA', 'AMpnKql9QxC3PQ2QT7FV8A', 'PRazsQdmQkiFipcptA4U2g', 'MhzSXyQERGSe3oI42skLLw', 'YAjczir9QlWwj2eyHjksQA']

**Comment by marco-c** [comment]
The query is no longer being used, and #359 has been filed to clean the code up.
