### ISSUE TITLE
Convert all functions in the taskcluster module to use the taskcluster library

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#306]
See https://github.com/mozilla/mozci/pull/305#discussion_r500186280.

**Comment by gauravpandeypes** [comment]
Hi, I would like to work on this issue.

I have gone through taskcluster.py file and understood that the functions need to be changed so that they use the taskcluster library. Could you explain a bit about the taskcluster library and explain the process for solving this issue.
This would be my first opensource contribution therefore needed some help.

**Comment by marco-c** [comment]
Hello @gauravpandeypes!

The taskcluster library documentation can be found on https://github.com/taskcluster/taskcluster/tree/main/clients/client-py (or https://pypi.org/project/taskcluster/).

The process for solving this issue is replacing the code in the functions from mozci/util/taskcluster.py to use the taskcluster library rather than manually making requests (`_do_request`). You can find an example usage of the taskcluster library in https://github.com/mozilla/code-coverage/blob/b77b89a2a94bc8291796f3f2233e020cda3403b7/report/firefox_code_coverage/codecoverage.py#L38.
For example, you should be able to reimplement https://github.com/mozilla/mozci/blob/65ef69502e9d834522599290138a99e0e7b296c0/mozci/util/taskcluster.py#L86-L88 as https://github.com/mozilla/code-coverage/blob/b77b89a2a94bc8291796f3f2233e020cda3403b7/report/firefox_code_coverage/codecoverage.py#L54-L56.

**Comment by gauravpandeypes** [comment]
Could you please go through the previous pull request and let me know if I am on the right track.
Thank You

**Comment by chichi012** [comment]
@marco-c I'm currently working on completing this
