### ISSUE TITLE
Add support for getting groups and groups results in the Treeherder data source

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#312]

**Comment by marco-c** [comment]
https://github.com/mozilla/treeherder/pull/6800 added the API.

**Comment by ahal** [comment]
Example: https://treeherder.mozilla.org/api/project/autoland/push/group_results/?revision=b63acc35871b4aad7d341b13f39f330a8d5ed099

**Comment by ahal** [comment]
I'll see if I can get this finished before my leave.

**Comment by ahal** [comment]
This is blocked on https://github.com/mozilla/treeherder/issues/6867

**Comment by ahal** [comment]
I'll put up my patches anyway, and once that other issue is fixed, they can be merged.

**Comment by ahal** [comment]
Actually, I think they can be merged anyway.. since if a task is missing group information, we'll download the errorsummary as a fallback..
