### ISSUE TITLE
Get classifications from treeherder data source

### ISSUE THREAD

**Issue by ahal** [mozilla/mozci#315]
This will depend on the API Cam added going live in production.

**Comment by ahal** [comment]
Note, this should create a new source that uses Treeherder's public API rather than the existing on which uses the ORM directly. Most people will not have access to the latter.

**Comment by camd** [comment]
We will be pushing this change to production today/this evening.  There is a migration that will block things for about 1/2 hour, so we have to time the deploy during a slow period.

**Comment by marco-c** [comment]
Link to the PR which introduced the API: https://github.com/mozilla/treeherder/pull/6796.
