### ISSUE TITLE
Change the query to get test results to only get group-level results and not test-level results

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#34]
Since we are going to schedule manifests, we don't need to get to the test-level results.

This will make the query return way less results, making the data gathering process way faster (and the ADR cache way smaller).

E.g.:
```
{
	"from":"unittest",
	"where":{"eq":{"repo.changeset.id":"18334489f92b5d0a73154f743c7c82b543ddc1f9"}},
	"groupby":"result.group",
	"format":"table",
	"limit":3000
}
```

Grouped by result.group, it's 1041 rows. Otherwise, it's 95641 rows.
We could even stop using `destination: url` for this query (push_tasks_results_from_unittest.query).

@ahal do you see any problem if we do this?

**Comment by marco-c** [comment]
@klahnakoski for this query https://github.com/mozilla/mozci/blob/master/mozci/queries/push_tasks_results_from_unittest.query#L1, we'd need to:
1 - Group by result.group, so we have one row per group;
2 - Aggregate in a way that: if any of the original rows have result.ok = False, the aggregation should be False; otherwise all the original rows have result.ok = True, and the aggregation should be True. Basically, a OR between the result.ok values. Is there such an aggregation?

1 is easy, could you help me with 2?

**Comment by marco-c** [comment]
I guess I can use "min", assuming False < True? :P

**Comment by marco-c** [comment]
What I have so far: https://activedata.allizom.org/tools/query.html#query_id=b126PIB_.

**Comment by klahnakoski** [comment]
Nice!

    "select":[{"value":"result.ok","aggregate":"min"}],

That may work, since Booleans get promoted to 0/1 when asked to participate in math.

We can verify consistency with 

    "select":{"name":"num_error", "value":{"when":{"result.ok", "else":1}}, "aggregate":"sum"} 

we can also look at the `meta.es_query` to ensure the correct query is sent

**Comment by klahnakoski** [comment]
for prosperity:  I typed the "when" expression, wrong; it is not valid JSON:

    "select":{"name":"num_error", "value":{"when":"result.ok", "else":1}, "aggregate":"sum"}

**Comment by marco-c** [comment]
Thanks @klahnakoski !

I've verified the results using this query https://activedata.allizom.org/tools/query.html#query_id=N9tS_wN5:
```
{
	"format":"table",
	"from":"unittest",
	"select":{
		"name":"num_error",
		"value":{"when":"result.ok","then":0,"else":1},
		"aggregate":"sum"
	},
	"groupby":["task.id","result.group"],
	"limit":3000,
	"where":{"eq":{"repo.changeset.id":"18334489f92b5d0a73154f743c7c82b543ddc1f9"}}
}
```
