### ISSUE TITLE
Replace voluptuous with faster validation library

### ISSUE THREAD

**Issue by ahal** [mozilla/mozci#440]
From taskgraph, we know that voluptuous is slow. Sarah also noticed a lot of time spent validating in her profiling runs. We can replace it with `validr` or `validx` which purport to be at least 3x faster.

**Comment by marco-c** [comment]
What if we offered an option not to validate the schema?

**Comment by ahal** [comment]
That could work too.. though since we don't have a ton of contacts I think
we should replace voluptuous either way. This shouldn't be super hard.

**Comment by ahal** [comment]
This was fixed
