### ISSUE TITLE
FakePush class in tests/test_data_sources.py is unused

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#475]
It should be removed.

https://github.com/mozilla/mozci/blob/eed7a2f4083da2952fe9f0526ecaa4778f714eab/tests/test_data_sources.py#L14-L17

**Comment by ryan-school2020** [comment]
i would like to take this issue. @marco-c

**Comment by marco-c** [comment]
@ryan-school2020, sure, feel free!
