### ISSUE TITLE
Some commits from ci-recipes are missing

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#5]
I think this was caused by https://github.com/mozilla/ci-recipes/commit/46e83cc9e3c5c6949071289a8bef1727e196b2d2, probably moving an old version of the code.

These commits were reverted (from newest to oldest):
https://github.com/mozilla/ci-recipes/commit/13b5ff5adb6c0b3cc320522f9cbb70e13ee72fae
https://github.com/mozilla/ci-recipes/commit/0be2a5b679fea784f96cffdc72ec493ded06bfd9
https://github.com/mozilla/ci-recipes/commit/4922ba06a92ea380660ac3741e1dc71fb1b8cbe1
https://github.com/mozilla/ci-recipes/commit/f5059c4bd4d023c8906107802da23796f05ae9a2

**Comment by ahal** [comment]
Apologies, should be fixed by:
https://github.com/mozilla/mozci/commit/c1d7d7bbc396d5ee7c4d937b2d727af1abea19db

Also sorry for messing up the history.
