### ISSUE TITLE
Implement the ability to classify tasks in Treeherder

### ISSUE THREAD

**Issue by ahal** [mozilla/mozci#506]
Classifying tasks is one of the most time consuming aspects of sheriffing. We should add the ability to add classifications in Treeherder.

This will depend on being able to authenticate with Taskcluster as well as Treeherder providing a public API to perform said action. It's possible this ends up being too much trouble.

**Comment by ahal** [comment]
Depends on #507

**Comment by marco-c** [comment]
An alternative that we discussed recently is to publish classifications somewhere, and let Treeherder consume them. This way we don't need to build a Treeherder API.

**Comment by marco-c** [comment]
> An alternative that we discussed recently is to publish classifications somewhere, and let Treeherder consume them. This way we don't need to build a Treeherder API.

This is what we have decided to do in the end, so we can close this issue as we don't need mozci to perform the classifications.
