### ISSUE TITLE
Use likely regressions in Push.classify_regressions unknown failures

### ISSUE THREAD

**Issue by La0** [mozilla/mozci#527]
Followup from https://github.com/mozilla/mozci/pull/526#discussion_r735472884

We could use the likely regressions instead of all the groups failing in the push to list unknown failures .

The idea may not work as the likely regressions are not exhaustive (being filtered of failures the ML model may benefit from).

**Comment by marco-c** [comment]
The comment from #526 is hard to find, so I'll copy it here:
> We might want groups_likely_regressions - real_failures - intermittent_failures here, rather than groups_failing_in_the_push - real_failures - intermittent_failures, I'm not sure.
Let's keep it as it is for now, and file an issue to consider switching to it (get_likely_regressions is already doing some initial filtering of failures that we might benefit from, but at the same time it is using sheriff classifications, so if we use it we can't validate this method's results with the sheriffs classifications).

**Comment by marco-c** [comment]
The problem about validating the method's results will go away after we fix #606.
