### ISSUE TITLE
hg.mozilla.org URLs are broken for release and try branches

### ISSUE THREAD

**Issue by ahal** [mozilla/mozci#53]
We hardcode `integration` into the HGMO urls:
https://github.com/mozilla/mozci/blob/c8648979e9b3dd7e0806e6d67df13e71eb20ce05/mozci/push.py#L20

This means we'll fail to download data there for central, try, release, etc. We should fix this :)

**Comment by marco-c** [comment]
Reopening as #59 is being reverted for now (with #63).
