### ISSUE TITLE
Add the possibility for the `classify` command to classify a range of pushes

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#535]
It could be useful to compare the classify command results with the actual decisions from sheriffs and see how often classify is correct.

**Comment by La0** [comment]
@marco-c So the CLI would either request:
- branch + revision
- one or several push id (integers)

**Comment by ahal** [comment]
See also issue #13

**Comment by EvaBardou** [comment]
> See also issue #13

@ahal As #13 isn't implemented for now, should I wait before working on this feature or should we allow the command user to provide multiple revisions on which we will iterate to instantiate various `Push` objects?

**Comment by marco-c** [comment]
@EvaBardou you can use the `make_push_objects` functions like we do in https://github.com/mozilla/bugbug/blob/ad35e6972783ae6ec71a37cd738d4f24aaa5e7b4/scripts/test_scheduling_history_retriever.py#L128-L132.
So the arguments would be branch, from_date, and to_date.

**Comment by marco-c** [comment]
The function is defined here: https://github.com/mozilla/mozci/blob/70196c6731110f1ace12f983e2f5d96d7d697f57/mozci/push.py#L1194.
It's basically returning a list of pushes, sorted by date.
