### ISSUE TITLE
Build cleo command to run Taskcluster decisions for classification

### ISSUE THREAD

**Issue by La0** [mozilla/mozci#541]
A new command named `decision-task` should be created and :
1. list all the running pushes from Treeherder api `push > list`
2. create a new children task for each push, using the mozci image and the `classify` command

A `--dry-run` mode should be implemented to run locally, without Taskcluster and see which tasks would be created.

**Comment by marco-c** [comment]
The hard part here is deciding which pushes to analyze.

**Comment by La0** [comment]
The [hook](https://community-tc.services.mozilla.com/hooks/project-mozci/decision-task-testing) is now running every 15 minutes to process the last 15 pushes.
