### ISSUE TITLE
Implement a command to evaluate the classification results by comparing them with reality

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#553]
The command should calculate statistics such as:
- how many pushes that we identified as bad were actually backed-out (true positives);
- how many pushes that we identified as bad were not backed-out (false positives);
- how many pushes that we identified as good were backed-out (false negatives);
- how many pushes that we identified as good were not backed-out (true negatives);
- percentage of pushes we weren't able to identify as good or bad.

**Comment by La0** [comment]
@EvaBardou You can already start working on that, even though we do not have published classifications yet (see #552):

- create a new command `push classify-eval` that can take either:
   - a single push id or revision
   - a date range
- list those `Push` instances
- detect the backout status for that push: there is already some data loading for that in `HgRev` (using json automation endpoint)

**Comment by La0** [comment]
We now have published classifications for a given push: you can fetch the artifact `public/classification.json` from the index `project.mozci.classification.<BRANCH>.push.<PUSH_ID>`

This is doable using the method [index.findArtifactFromTask](https://docs.taskcluster.net/docs/reference/core/index/api#findArtifactFromTask) from the Taskcluster Python client
