### ISSUE TITLE
Some "intermittent" classifications have empty list of tasks

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#563]
See for example https://community-tc.services.mozilla.com/tasks/index/project.mozci.classification.mozilla-central.push/989898.

I'm attaching the classifications JSON file.
[classification.zip](https://github.com/mozilla/mozci/files/7604152/classification.zip)
There are some groups under "intermittents" which have an empty list of tasks, e.g. accessible/tests/mochitest/attributes/a11y.ini.

**Comment by La0** [comment]
As discussed yesterday, we need to track down the different groups and their assignation in the `classify_regressions` method as it's most probably the source of the bug (every intermittent group has some tasks with results `PASS`).

A relatively simple approach (given we can have thousands of groups) would be to generate a CSV file, so we can load into an Excel-like application and filter/search it easily.

@EvaBardou can work on this and add a method in `mozci.logging` named `generate_groups_csv` that will take 3 arguments:
- a file path to write the CSV (example `/tmp/xxx.csv`)
- a list of `GroupSummary` objects (this will be `self.group_summaries.values()`
- a dict of assignations (str) => list of group name to know where each group belong: each assignation will generate a column, where a value `yes` will be present if the group is in that list of groups

```python
generate_groups_csv(
  "/tmp/output.csv",
  self.group_summaries.values(),
  {
    "likely_regressions": groups_likely_regressions,
    "high": groups_high,
    "low": groups_low,
   ...
  }
)
```

Make sure all assignations list is a list of string (and not a list of GroupSummary), so you are able to compare each group summary name against that list.

We'll need to have these columns in the CSV output:
- group name
- group status (from `GroupSummary.status`)
- nb_tasks (filtering tasks for that group name)
- nb_tasks_ok (filtering tasks for that group name & result OK)
- likely_regressions
- high
- low
- cross config failure
- failing
- intermittent
- no_confidence
- real_failures
- intermittent_failures
- unknown_failures

Once we have that, we may detect incorrect behaviours :crossed_fingers:

**Comment by marco-c** [comment]
I would debug directly the problem by choosing one of the groups which is marked as intermittent but has no tasks associated with it, and log everything everywhere about it (so filter the logging directly in the code itself) to understand the problem.

It doesn't hurt to add this logging function though if you are more comfortable debugging that way.
