### ISSUE TITLE
Implement a shared cache between the classification tasks

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#564]
Right now each classification task is totally separate, which means they are retrieving the same data multiple times.
We should introduce a shared volume between the classification tasks to avoid that.

**Comment by webbdays** [comment]
@marco-c 
I would like to work on this issue.
Please provide code location for that.

**Comment by webbdays** [comment]
@marco-c @La0 

Please provide the example for classification task. What are the things on which the classification task is performed ?

**Comment by marco-c** [comment]
@webbdays this is not an easy issue to solve. @La0 is working on it.

**Comment by webbdays** [comment]
Ok

**Comment by La0** [comment]
The cache is now enabled ([demo](https://community-tc.services.mozilla.com/tasks/groups/dWDbOHzHSdiGmXGsFNUyrw))
