### ISSUE TITLE
Support getting data for try pushes

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#58]
We'd need to compare the try push to its parent push on mozilla-central or autoland.

**Comment by marco-c** [comment]
Depends on #127.

**Comment by marco-c** [comment]
Note: some of the things we currently assume will need to change to be optional (e.g. we can't ignore pushes which were not backed out / bustage fixed for try).

**Comment by ahal** [comment]
Now that #127 is closed, what's left to do here?

Off the top of my head, I guess we won't have any child pushes to inspect. So we need to do the best we can finding regressions without children.

Depends on #80

**Comment by marco-c** [comment]
And the other thing is definitely not returning {} early when a push was not backed-out nor bustage fixed (since on try things are not backed out nor bustage fixed).
