### ISSUE TITLE
`push.classify_regressions()` produce errors originating from a parent's revision

### ISSUE THREAD

**Issue by chichi012** [mozilla/mozci#587]
For a given push object, for example, push = Push('b6a94bff9d8e0c31fd28b848bbad84a23731e9c0','try') ,
`push.classify_regressions()`  produced some errors. Some of the error logs are seen below.  `xpcshell.ini` files originate from the parent revision.

19:07:08.561 | ERROR    | mozci.data.sources.artifact:64  - Some groups in FR_bhpkAR7-FKdrYThH7Xw are missing results: 
{'browser/components/migration/tests/unit/xpcshell.ini', 'devtools/shared/qrcode/tests/xpcshell/xpcshell.ini'}

`19:07:09.000 | ERROR    | mozci.data.sources.artifact:64  - Some groups in ehrnCDlqQju3CeooLGutSg are missing results: {'browser/base/content/test/plugins/browser.ini', 'dom/cache/test/browser/browser.ini', 'dom/u2f/tests/browser/browser.ini'}

`19:07:28.832 | ERROR    | mozci.data.sources.artifact:64  - Some groups in OSIBkgxCRTWjK4XXGDKr1Q are missing results: {'editor/txmgr/tests/crashtests/crashtests.list', 'gfx/tests/crashtests/crashtests.list', 'editor/libeditor/crashtests/crashtests.list'}

19:07:28.996 | ERROR    | mozci.data.sources.artifact:64  - Some groups in Lb8VQ42KTseWLWKGhXaxiQ are missing results: {'dom/mathml/crashtests/crashtests.list', 'layout/generic/crashtests/crashtests.list'}

**Comment by marco-c** [comment]
This is a known issue (https://bugzilla.mozilla.org/show_bug.cgi?id=1704142). You can ignore it for now (it should be rare enough).

**Comment by chichi012** [comment]
Okay, thanks for the clarification.

**Comment by jmaher** [comment]
using mozci to green up tests on try, this will most likely be a regular issue- ideally we can adjust this to debug messages or something.
