### ISSUE TITLE
Add an option to choose the minimum number of configurations to consider a failure as cross-config and maximum to consider it as not-cross-config

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#605]
If we run a test on a single configuration and it fails, should we consider it as a cross config failure or not?
If we consider it, we mark more pushes as BAD.
If we don't consider it, we mark more pushes as GOOD or UNKNOWN.

**Comment by La0** [comment]
@marco-c So have you given some thought on that ? It gets too philosophical for me

**Comment by marco-c** [comment]
@La0 for the evaluations, I think we should run the classify-eval command before/after applying the change and then see which performs better.

**Comment by marco-c** [comment]
Perhaps as part of this we should add an option to make https://github.com/mozilla/mozci/blob/e56f55668be18c14e861fbcce2bb63f0b1e123e0/mozci/task.py#L486 configurable, a bit like `minimum_count` in https://github.com/mozilla/mozci/blob/e56f55668be18c14e861fbcce2bb63f0b1e123e0/mozci/task.py#L455.

**Comment by marco-c** [comment]
> Perhaps as part of this we should add an option to make
> 
> https://github.com/mozilla/mozci/blob/e56f55668be18c14e861fbcce2bb63f0b1e123e0/mozci/task.py#L486
> configurable, a bit like `minimum_count` in
> 
> https://github.com/mozilla/mozci/blob/e56f55668be18c14e861fbcce2bb63f0b1e123e0/mozci/task.py#L455
> .

Yeah, let's do that.
`is_cross_config_failure` should become:
```Python
    def is_cross_config_failure(self, minimum_count: int = 2) -> Optional[bool]:
        states = [
            result.ok
            for task in self.tasks
            for result in task.results
            if result.group == self.name
        ]

        nb = len(states)
        nb_passed = sum(states)  # Number of True booleans in the states list
        nb_failed = nb - nb_passed

        # If the group run on fewer than `minimum_count` tasks, we don't have enough information to tell.
        if nb < minimum_count:
            return None

        # A group is a cross config failure when it is failing in all tasks and not
        # only in some.
        return nb_failed > 0 and nb_passed == 0
```
and we have to adjust tests.

Then, we can add a parameter to `Push.classify_regressions` similarly to #641.
