### ISSUE TITLE
Be more verbose on errors when running CLI commands

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#616]
For example, https://github.com/mozilla/mozci/blob/c130bb7055d77b9b551c348f9d85f535ee169e39/mozci/console/commands/push.py#L135 is eating the exception and just printing str(Exception), so we are missing the stacktrace that would help in fixing #615.

**Comment by La0** [comment]
There should also be a companion PR on community-tc-config that enable mail notification on failures

**Comment by La0** [comment]
@EvaBardou You should also raise when there are issues on the notifications (mail or matrix)

**Comment by EvaBardou** [comment]
> @EvaBardou You should also raise when there are issues on the notifications (mail or matrix)

@La0 already done in https://github.com/mozilla/mozci/pull/660

**Comment by EvaBardou** [comment]
> There should also be a companion PR on community-tc-config that enable mail notification on failures

Maybe, we should open a dedicated issue for this part, giving instructions on who to ping via email and which Matrix room should be notified. We may not want to alert the same people as for the `BAD` evolution notifications...
