### ISSUE TITLE
Expand classification comparison to failures missed by mozci

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#637]
Currenty, with #636, we compare mozci classify results with sheriffs' results. By starting from mozci classify results, we are not including in the evaluation those failures which were classified by sheriffs but where mozci didn't know what to do.

For intermittent failures, we simply have to go through all group summaries of the push and compare their classifications with mozci classify results in the `intermittent` list.
For real failures it's a bit more difficult, because we have to get failures from following pushes too (in case a given group failed because of a push but didn't run on the push itself). We can get all failures starting from the push of interest and ending with its backout, and filter them by the "fixed by commit" note. Or more simply, we can just use `get_likely_regressions` with the `historical_analysis` parameter set to True.

**Comment by La0** [comment]
@EvaBardou will work on that this week
