### ISSUE TITLE
Extend the classify command to perform backfills (and choose between retriggers or backfills) when it needs more information

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#654]
The algorithm behind the classify command isn't always able to give a decision between "good" or "bad" and sometimes needs more information in order to be sure.

When a situation like this happens and the classify command returns "unknown", it should automatically identify and perform the set of actions (retriggers and/or backfills) that would be necessary to gather enough information.

#619 implemented support for retriggers, but retriggers might not always be the best action. See https://github.com/mozilla/mozci/pull/619#issuecomment-1033590959.

Depends on https://github.com/mozilla/mozci/issues/504 and https://github.com/mozilla/mozci/issues/508 and https://github.com/mozilla/mozci/issues/743.

**Comment by marco-c** [comment]
`real_failures` is the intersection of `groups_regressions`, `groups_relevant_failure`, and `groups_high`.
`groups_high` is not going to change even if we backfill or retrigger, as it only depends on the results from the test selection algorithm.
`groups_relevant_failure` can change if we perform retriggers (grow, if the task fails on the retrigger too).
`groups_regressions` can change if we perform backfills (shrink, if `use_possible_regressions` is True and the task fails on a parent too; grow, if `use_possible_regressions` is False and the backfill causes a regression to move from possible to likely).

`all_intermittent_failures` is the intersection of `groups_non_relevant_failure` and `groups_low.union(groups_no_confidence)`.
`groups_low.union(groups_no_confidence)` is not going to change even if we backfill or retrigger, as they only depend on the results from the test selection algorithm.
`groups_non_relevant_failure` can change if we perform retriggers (shrink, if the task doesn't fail on the retrigger too).

I propose the following:
- take `group_regressions` that are also in `groups_high` and, if they are not in `groups_relevant_failure` because there are not enough runs (so `g.is_cross_config_failure` and `g.is_config_consistent_failure` are both None), then retrigger a number of times to reach `minimum_count`;
- take all groups that run in the push and are in `groups_low.union(groups_no_confidence)` and, if they are not in `groups_non_relevant_failure` because there are not enough runs (so `g.is_cross_config_failure` and `g.is_config_consistent_failure` are both None), then retrigger a number of times to reach `minimum_count`;
- take `group_regressions` that are possible regressions but not likely regressions and are also in `groups_high` and backfill them (with a limit of X failures to backfill, we can choose them starting from those that are also in `groups_relevant_failure` and sorting by confidence).

**Comment by La0** [comment]
We could implement the 2 first points in a dedicated MR that would list all groups that need a retrigger.

**Comment by marco-c** [comment]
> @marco-c Do you prefer that we trigger `backfills` and `retriggers` directly in the `classify_regressions()` function using a boolean to enable the possibility, for example `classify_regressions(..., can_retrigger_and_backfill=True)` would be able to perform those two actions? Or would you rather like that `classify_regressions()` returns two new lists of groups `groups_to_be_retriggered` (with the `minimum_count` somewhere) and `groups_to_be_backfilled`?

I prefer the second option.


> > then retrigger a number of times to reach `minimum_count`
> 
> What should be the value of `minimum_count`?

The values we pass to check for config consistent failures: https://github.com/mozilla/mozci/blob/6cf1980876d9c48562e983728c8f253ca9cb7073/mozci/push.py#L1139 for real and https://github.com/mozilla/mozci/blob/6cf1980876d9c48562e983728c8f253ca9cb7073/mozci/push.py#L1154 for intermittents.

> 
> Since `retrigger()` and `backfill()` functions are available on `Task` objects, should all tasks on a group (`GroupSummary.tasks`) be retriggered/backfilled? Or maybe just the failing ones (`GroupSummary.failing_tasks`)?

Only the failing, but in theory we should only have failing tasks with the conditions specified above.
If there is more than one failing, we should retrigger/backfill only one of them.

> > with a limit of X failures to backfill
> 
> Should this "limit" be parametrizable? What should be its default value?

Yes, let's use 3.
