### ISSUE TITLE
Script classification batch execution

### ISSUE THREAD

**Issue by La0** [mozilla/mozci#693]
We need a script (not a new command for now) that allows someone to run a LOT of classifications with different parameters on several pushes.

By default, we would analyze all pushes from the last month.

We would combine all possible parameters (using `itertools.product`):

```
intermittent_confidence_threshold = 0.5, 0.7, 0.9
real_confidence_threshold = 0.7, 0.8, 0.9
use_possible_regressions = True, False
unknown_from_regressions = True, False
consider_children_pushes_configs = True, False
cross_config_counts = (2, 2), (2, 3), (2, 5)
consistent_failures_counts = (2, 3), (2, 5)
```

The script would output 2 things:
1. a CSV file with the following columns (each line is a `classify()` execution):
   - an unique UUID per run
   - the Mozilla push ID
   - each parameter with its value
       - intermittent_confidence_threshold
       - real_confidence_threshold
       - use_possible_regressions
       - unknown_from_regressions
       - consider_children_pushes_configs
       - cross_config_counts
       - consistent_failures_counts
   - the classification result
   - the time spent classifying
   - the `datetime.now()`
2. a JSON file with the full output from `classify()`, identified by `{UUID}.json` and prettyfied.

This should allow @marco-c to analyze the behaviours on various pushes & parameters.

:bulb: A nice followup would be to support parallelism as a lot of time will be spent waiting on other remote systems.

**Comment by La0** [comment]
Runs from last month are [available online](http://data.teklia.com/mozilla/mozci-runs-2022-03-18.csv)

There are 718848 runs in that file !

**Comment by marco-c** [comment]
@EvaBardou could you also write a script, or add some code to the script you wrote in #694, to sort the results by most correct intermittent/real or least wrong intermittent/real?

Basically, the script should compute the results (wrongly classified as intermittent / correctly classified as intermittent / wrongly classified as real / correctly classified as real, similarly to ClassifyEval) for each configuration, then allow sorting the configurations by one of the four metrics.
