### ISSUE TITLE
If a group is still running on a parent push, don't consider a regression as new

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#697]
E.g. in case of backfills, there is a chance a group will finish on a child push before a parent push.
If there is a failure happening on a push, and the same group is still running on the parent, then we can't tell if the failure is new or pre-existing.

Not sure we can identify this situation though, as the task running the group is still running, and so errorsummary.log is not available yet.

**Comment by marco-c** [comment]
For example, on 58fa4a284e789a372e56394703427e59baa34011 we had devtools/client/debugger/test/mochitest/browser.ini running and failing. On its parent push the task that was supposed to run the same group was retried, so it ended up running (and failing) after the equivalent task on the child push.
While the task on the parent was still running, the task on 58fa4a284e789a372e56394703427e59baa34011 was retriggered 5 times and failed 5 times, so we were considering devtools/client/debugger/test/mochitest/browser.ini as a regression of 58fa4a284e789a372e56394703427e59baa34011.

**Comment by La0** [comment]
@marco-c In this case, how do we consider a group to be running:
- when any task of the group is not in a final state ?
- when we did not get all task results ?
- both ?

I *think* the second option is either to implement

**Comment by marco-c** [comment]
There is one problem to figure out: right now until a task is complete, we don't know what groups it run!
We need to figure out if it's feasible to know which groups a task is going to run even before it runs or while it is still running.

Otherwise, we have to consider any group as potentially still running on any given push, unless it already run on that push or unless all tasks on that push are complete.

@ahal do you know if we can retrieve the groups that a task is going to run? Maybe from some artifact in the decision task? Or from the task definition?

**Comment by marco-c** [comment]
We have MOZHARNESS_TEST_PATHS in the task definition that lists the groups that are going to run (this is only for some test suites, not all, so we'll need to have different paths of execution for different test suites).

We could add a `is_running` function on the Push that takes as input a group and:
1) iterates through all tasks to find those that are not complete;
2) if the group belongs to a test suite where MOZHARNESS_TEST_PATHS is not available, then we return True if there is any task still running for that test suite;
3) if the group belongs to a test suite where MOZHARNESS_TEST_PATHS is available, then we return True if there is any task still running where the group is in the MOZHARNESS_TEST_PATHS for that task.

**Comment by marco-c** [comment]
> @marco-c A few questions:
> 
> > iterates through all tasks
> 
> So we need to iterate over all tasks on the `Push` using `self.tasks` right?

Yes.

> > to find those that are not complete;
> 
> Do you mean tasks where `state == "completed"` or tasks that aren't in a final state (`completed`, `failed`, `exception`)?

Tasks that are not in a final state.
 
> > if the group belongs to a test suite where MOZHARNESS_TEST_PATHS is not available
> 
> I don't understand how to check for that? Can I retrieve a test suite definition? How can I know if a group belongs to a test suite?

We could check the test suite from the names of the tasks associated to the group, but then we'd need to have a hardcoded list of test suites...
A better way, automatic, to do that would be to check if the tasks associated to the group have the `tests_grouped` value set to 1 in their tags (or the MOZHARNESS_TEST_PATHS value in their payload). If they don't, then MOZHARNESS_TEST_PATHS is not available for the test suite they belong.
In the Task class:
```Python
def is_tests_grouped(self):
    return self.tags.get("tests_grouped") == "1"
```

In the Push class:
```Python
if all(task.is_tests_grouped() for task in group_summary.tasks):
    for task in still_running_tasks:
        if group in task.payload["MOZHARNESS_TEST_PATHS"]:  # the check is actually more complex than this because of the format of the data, we need to check if group is in the lists that are the values of the MOZHARNESS_TEST_PATHS dict
            return True # group is still running
else:
    # check if any task associated to the group have the same `test-type` tag as any of the tasks still running on the push
```
