### ISSUE TITLE
Add some queries to make sure data from ActiveData is as expected

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#71]
The way I see this working: we add the queries in mozci, we add a cron job somewhere (probably Taskcluster, or even Travis) to make sure the results from the queries are as we expect.

We could also do this in ci-recipes instead of mozci.

We could add one to make sure that all suites (except a blacklist) are generating manifest information. Something like:
```
{
	"from":"unittest",
	"groupby":"run.suite.name",
	"where":{"and":[
		{"eq":{"etl.id":0}},
		{"missing":"run.suite.groups"},
		{"gte":{"action.start_time":{"date":"today-1day"}}}
	]},
	"limit":1000
}
```

We could add another to make sure unittest results from all manifest-based suites (except a blacklist) have information on what manifest the result corresponds to. Something like:
```
{
	"from":"unittest",
	"groupby":"run.suite.name",
	"where":{"and":[
		{"exists":"run.suite.groups"},
		{"missing":"result.group"},
		{"gte":{"action.start_time":{"date":"today-1day"}}}
	]},
	"limit":1000
}
```

**Comment by ahal** [comment]
Here are some tests in the `adr` repo that run in a CRON task in Travis and hit live ActiveData:
https://github.com/mozilla/adr/blob/master/test/test_recipes_integration.py

We could follow the same setup here. Note, I'm not opposed to switching to Taskcluster either, though don't have any experience setting it up in Github.

**Comment by ahal** [comment]
Oops, the tests actually live in the `active-data-recipes` repo now:
https://github.com/mozilla/active-data-recipes/blob/master/test/test_recipes_integration.py

**Comment by marco-c** [comment]
> Here are some tests in the adr repo that run in a CRON task in Travis and hit live ActiveData:
https://github.com/mozilla/adr/blob/master/test/test_recipes_integration.py

> We could follow the same setup here. Note, I'm not opposed to switching to Taskcluster either, though don't have any experience setting it up in Github.

Sounds great to me, we can do this for now as it's quicker and switch to Taskcluster in the future.

Another test to perform: get all recent groups (both run.suite.groups and result.group) and make sure they are all not "bad" (https://github.com/mozilla/mozci/blob/2928c0f1833ec341a06fdf47c75f59765f5309e9/mozci/task.py#L45-L56).
