### ISSUE TITLE
Send a notification in the Matrix channel when a backfill is finished

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#728]
Sheriffs often trigger backfills and have to periodically check if the tasks triggered by the backfill are finished. It would be nice to implement a notification to the Matrix channel to notify them instead, so they don't have to periodically check.

**Comment by La0** [comment]
Here the plan discussed yesterday: we'll use **existing** Taskcluster index on backfill (parent) tasks, and find these tasks from a new Taskcluster hook.

A new command named `check-backfill` will be created, and its general workflow will be:
1. list an arbitrary number of recent pushes on a branch (100 last pushes on autoland by default)
2. for each push, check if there is are indexed tasks under `index.gecko.v2.<BRANCH>.revision.<REVISION>.taskgraph.actions` ([example](https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.autoland.revision.3be61b332b33b42479c30762a75d3b77a3a25816.taskgraph.actions))
3. for each indexed tasks, list the children tasks (using [list dependant tasks API](https://docs.taskcluster.net/docs/reference/platform/queue/api#listDependentTasks))
4. load each indexed task definition and look up the extra metadatas:
    - if there is `action` key and `action.name == "backfill-task"`, we'll use this task ([example](https://firefox-ci-tc.services.mozilla.com/tasks/Q9wE60RyRS-vfpyfb9DvhQ))
    - otherwise skip this task
5. for each **finished** backfll task, check if there is an indexed task (on community-tc, not firefox-ci-tc) with pattern `project.mozci.check-backfill.<BRANCH>.<REVISION>.<BACKFILL_TASK_ID>`
   - if this index exists (don't load artifacts), skip this task
6. time to publish a matrix notification (same as for classification state change, same channel, but different content): "Backfill task <task_id> for <BRANCH> / <REVISION>" completed (@marco-c If you want more specific content, please comment !)
7. finally, add an index to the current running task using the pattern mentionned above

Needed CLI parameters:
- `--branch`, default to `autoland`
- `--nb-pushes`, default to 100

**Comment by marco-c** [comment]
> 6\. time to publish a matrix notification (same as for classification state change, same channel, but different content): "Backfill task <task_id> for  / " completed

We only have to publish the notification (and add to the index) when a whole backfill group is finished.
Once you get all backfill tasks, you need to check that all tasks belonging to the same backfill group finished (I think the only way to do that for now is by checking the "symbol" in the treeherder section of the task definition).

**Comment by La0** [comment]
We discussed the issue today, and @EvaBardou will work on it early next week
