### ISSUE TITLE
Define autoclassification parameters in the config secret

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#735]
The parameters to https://github.com/mozilla/mozci/blob/b466f55213cfe8b99b10f84610e2e4272c09e559/mozci/push.py#L1218-L1227 should be defined in the secret so we can periodically check the best ones and simply update the secret instead of having to modify the code and push a new release.

**Comment by La0** [comment]
@marco-c So we would remove the CLI options to specify these and only support through the config (either from local file or from Taskcluster secret) ?

**Comment by marco-c** [comment]
Yeah, or have both CLI options and config
