### ISSUE TITLE
Implement ability to perform backfills on a push

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#743]
See also #508, which implemented retriggers.

To trigger backfills, we need to trigger a backfill action (IIRC there are two potential actions, one for a single backfill on a single push and one for a backfill on multiple pushes).
Here's an example of action triggering (in this case "add-new-jobs" action): https://github.com/mozilla/code-review/blob/47d1b78b80e7f2d59b2d4dd3ef95064f1b2d661d/events/code_review_events/bugbug_utils.py#L240.

**Comment by La0** [comment]
@marco-c How do we find the correct hook to trigger the backfill ? There are a bunch of them on firefox-ci-tc hooks (in `proj-gecko`).

In the code-review bot example, the hook ID is found from a specific indexed task (from its payload). So my question is : what's the entrypoint here ?

**Comment by marco-c** [comment]
Similarly to code-review bot, we should load the actions.json file from the decision task of the autoland push and then trigger the hook with the name "backfill".
E.g. for https://treeherder.mozilla.org/jobs?repo=autoland&selectedTaskRun=cIysKHAiSBOhhHrvgKMo1w.0&searchStr=decision&revision=5f90901a36bb9735cef6dc7d746d06880a61226d it would be https://firefoxci.taskcluster-artifacts.net/cIysKHAiSBOhhHrvgKMo1w/0/public/actions.json, which has:
```
{
      "context": [
        {}
      ],
      "description": "Given a task schedule it on previous pushes in the same project.",
      "extra": {
        "actionPerm": "backfill"
      },
      "hookGroupId": "project-gecko",
      "hookId": "in-tree-action-3-backfill/9ffde487f6",
      "hookPayload": {
        "decision": {
          "action": {
            "cb_name": "backfill",
            "description": "Given a task schedule it on previous pushes in the same project.",
            "name": "backfill",
            "symbol": "Bk",
            "taskGroupId": "cIysKHAiSBOhhHrvgKMo1w",
            "title": "Backfill"
          },
          "push": {
            "owner": "mozilla-taskcluster-maintenance@mozilla.com",
            "pushlog_id": "163357",
            "revision": "5f90901a36bb9735cef6dc7d746d06880a61226d"
          },
          "repository": {
            "level": "3",
            "project": "autoland",
            "url": "https://hg.mozilla.org/integration/autoland"
          }
        },
        "user": {
          "input": {
            "$eval": "input"
          },
          "taskGroupId": {
            "$eval": "taskGroupId"
          },
          "taskId": {
            "$eval": "taskId"
          }
        }
      },
      "kind": "hook",
      "name": "backfill",
      "schema": {
        "additionalProperties": false,
        "properties": {
          "depth": {
            "default": 19,
            "description": "The number of previous pushes before the current push to attempt to trigger this task on.",
            "maximum": 25,
            "minimum": 1,
            "title": "Depth",
            "type": "integer"
          },
          "inclusive": {
            "default": false,
            "description": "If true, the backfill will also retrigger the task on the selected push.",
            "title": "Inclusive Range",
            "type": "boolean"
          },
          "retrigger": {
            "default": true,
            "description": "If False, the task won't retrigger on pushes that have already ran it.",
            "title": "Retrigger",
            "type": "boolean"
          },
          "times": {
            "default": 1,
            "description": "The number of times to execute each job you are backfilling.",
            "maximum": 10,
            "minimum": 1,
            "title": "Times",
            "type": "integer"
          }
        },
        "type": "object"
      },
      "title": "Backfill"
    }
```

**Comment by La0** [comment]
Thanks for the info.

So in mozci, we use `Push.decision_task` which already exists, then fetch the `actions.json`, lookup the first action with `name == "decision"`, and trigger its hook.

@EvaBardou can work on that with these informations :+1: 

Finally @marco-c , the backfill hooks has several parameters (all with a default value, so it's not blocking):
- `depth`, default 19
- `inclusive`, default `False`
- `retrigger`, default `True`
- `times`, default 1

Do you want to control these values ?

**Comment by marco-c** [comment]
I think we can keep the parameters at their default value. @Archaeopteryx is that what sheriffs usually do when backfilling?

**Comment by Archaeopteryx** [comment]
>     * `times`, default 1

If it's a permanent failure, then `1` is sufficient. If it's intermittent, it has to be run multiple times depending how often it failed. `5` is a common value for intermittent failures.

The backfill action is [defined in mozilla-central](https://searchfox.org/mozilla-central/rev/1c391443f770eddc7cde9e52dba5ef50cc233c06/taskcluster/gecko_taskgraph/actions/backfill.py), Treeherder fetches the available actions [here](https://github.com/mozilla/treeherder/blob/644d808a5cfe0cf6d85ed43f7bdfef054278b944/treeherder/services/taskcluster.py#L72-L95).

**Comment by EvaBardou** [comment]
> taskId: the ID of the task we want to backfill (assuming "backfill" is a method of the Task class, then we can simply use self.id).

@marco-c Wasn't I supposed to implement the `backfill` method on the `Push` class?

**Comment by marco-c** [comment]
@EvaBardou maybe better on the Task class, but the difference is negligible so feel free to add it to the Push class if it's easier. If you add it to the Push class, then a Task instance should be a parameter of the function (so you can get the taskId from the paramter).
