### ISSUE TITLE
Implement retriggers using retrigger action or use firefox-ci client when creating task

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#765]
The retrigger capability is implemented by simply copying a task (https://github.com/mozilla/mozci/blob/8daaaf08fd5d2b7f29f0d48ff2ddb2ef21c72216/mozci/task.py#L266), and creating a new one (https://github.com/mozilla/mozci/blob/8daaaf08fd5d2b7f29f0d48ff2ddb2ef21c72216/mozci/util/taskcluster.py#L156).
There is also a retrigger action though, maybe we should use that action instead of manual implementation of retrigger? @ahal @jmaher wdyt?

**Comment by jmaher** [comment]
I am all for reusing existing functionality- I caveat that with I have been out for a couple of weeks and I might not remember all the quirks with retrigger vs rerun vs create_task

**Comment by marco-c** [comment]
Currently retriggers are not actually working given that we are on community-tc and the tasks are on firefox-ci (https://github.com/mozilla/mozci/blob/81076cc82a0cf5fab9302c7c13cd0aafda17472d/mozci/util/taskcluster.py#L156).
So, we have to either switch to using the action, or use the firefox-ci client that we have to create the task (adding the credentials at https://github.com/mozilla/mozci/blob/e519794c9b3bba57dcad8d53026735cccc64c5f4/mozci/util/taskcluster.py#L158 like we do at https://github.com/mozilla/mozci/blob/e519794c9b3bba57dcad8d53026735cccc64c5f4/mozci/task.py#L319).
