### ISSUE TITLE
Hang waiting for `future.result` in `Push.group_summaries`

### ISSUE THREAD

**Issue by ahal** [mozilla/mozci#79]
I was trying to grab the regressions from a `Push` and experienced a hang (waited about 30 minutes). After ctrl-c'ing, it was waiting for `future.result` here:
https://github.com/mozilla/mozci/blob/0333f53abc688e70d5726ff91f4829672e71513e/mozci/push.py#L315

The push I was inspecting was fairly recent, so it's quite possible it was trying to grab data that didn't exist in ActiveData. However we should try to fail fast if this is the case. At the very least have a timeout to prevent indefinite hangs.

**Comment by marco-c** [comment]
Possibly the group data was missing in ActiveData, and so we started downloading the artifacts from S3.
It can be pretty slow, on my connection 30 minutes would probably be a reasonable amount of time :P
On Taskcluster, it takes a few seconds.

**Comment by marco-c** [comment]
NOTE: not sure if that was the case here or if we just hanged.

**Comment by marco-c** [comment]
I think I remember fixing this hang.
