### ISSUE TITLE
replace @memoized_property with @memoize

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/mozci#87]
The use of `@memoized_property` has trivial benefit.  It hides a large amount of work behind attribute access, and interferes with debugger attempting to navigate those "attribute".  Please replace with `@memoize` and call the methods.

**Comment by klahnakoski** [comment]
Also, once removed, the objects can be serialized to JSON during caching.

**Comment by ahal** [comment]
I'd push back on the "trivial benefit" part here. API surfaces are important, and hiding logic behind properties is a pretty standard Pythonic way of building useable APIs. Do you have an example of where this interferes with a debugger? Any Python debugger should be able to step into properties no problem. Or are you talking about the `memoized_property` code itself being problematic? (Fwiw, I would expect `memoize` to be equally problematic if this is what you mean).

Here are their sources:
https://github.com/mozilla/adr/blob/master/adr/util/memoize.py

(they are just pulled from the ones we use in `mozilla-central`)

**Comment by ahal** [comment]
Oh, I wonder if it's because `memoized_property` doesn't call `functools.update_wrapper` like `memoize` does:
https://github.com/mozilla/adr/blob/master/adr/util/memoize.py#L13

That definitely seems like a bug (which exists in `mozilla-central` too fwiw).

**Comment by klahnakoski** [comment]
The IDE will attempt to access all the properties at once.  This is slow, and times out:  meaning none of the object properties are easily accessible:  Sure, I can click on each property and expand it, maybe.  Also, the JsonSerializer() is confused by the use of properties: it can not serialize them; once the heavy properties are turned back into functions, the JSON cache works, the IDE can show the full content of the objects in the debugger.

> hiding logic behind properties is a pretty standard Pythonic way of building useable API

I agree, but only in the case where property access is reasonable fast: Where a property hides some convenient but simple derivative of other local data.

Attribute accessors imply low computational cost, and imply local data. This assumption is used by humans and machines; attributes are light weight, so we assume they can be access quickly.  Functions are assumed expensive and indicate there may be significant resources backing its implementation.  Attributes are data, functions are operations.

**Comment by klahnakoski** [comment]
I am not aware of a problem with the `memoized_property` code

**Comment by armenzg** [comment]
Could you please provide a set of steps to reproduce? Even screenshots of the IDE if it helps.

**Comment by klahnakoski** [comment]
@armenzg this issue is a difference of priorities: ahal wants to give callers clean code; I think the code is obfuscating resource usage.
