### ISSUE TITLE
Build alternatives to the `regression` functions which work at the manifest level

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#9]
Once #3 is fixed.
The logic (and so the code) should possibly be the same, just working on manifests rather than task.

**Comment by marco-c** [comment]
We basically need an alternative to LabelSummaries that works at the manifest level.
I guess the classification of a task can be applied to all results of a task? Wdyt @ahal?

**Comment by ahal** [comment]
Or maybe we can adjust `LabelSummary` to remove the chunk number, so we can still group manifests / failures by platform/suite/variant/etc, but just bunch all the chunks together. Then `LabelSummary` could own a list of manifests that ran in that grouping (potentially with their own dataclass, or maybe just simple dict).
