### ISSUE TITLE
Use words to describe status

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/mozci#92]
Please convert enums to something that can be serialized as JSON; something descriptive.  

Instead of

```
class Status(Enum):
    PASS = 0
    FAIL = 1
    INTERMITTENT = 2
```

use

```
class Status(object):
    PASS="pass"
    FAIL="fail"
    INTERMITTENT="intermittent"
```

No other code need to change, and the values can be serialized to humane JSON strings

**Comment by ahal** [comment]
You just have to use the `name` attribute. For example:
```
> status = Status.PASS
> status.name
"PASS"
```

That way you can use strings if you like, but we can also use greater than comparisons to e.g filter all statuses that are worse than PASS. Would that solve your use case?

**Comment by ahal** [comment]
I'm not terribly opposed to turning them into strings either fwiw.. just thought this might be easier all around.

**Comment by klahnakoski** [comment]
@ahal if these values remain enums, then I will eventually add enum serialization to the libraries that must encode them.  It is up to you.

**Comment by klahnakoski** [comment]
@ahal ... so keep them as enums; I am sure there are plenty of other code with enums that must be dealt with.

**Comment by ahal** [comment]
Ok, might as well just change them to strings then. Being able to compare with greater than comparisons isn't super compelling anyway.

**Comment by ahal** [comment]
I mid-aired a bit. Talked to Kyle on IRC and he's going to add support for this to his JSON serializer.
