### ISSUE TITLE
mozci fails to run in CI due to poetry lockfile mismatch and credentials for gitlab

### ISSUE THREAD

**Issue by jmaher** [mozilla/mozci#946]
poetry released in early December 2022 which has some backwards compatibility issues with their lockfiles.  This is failing in our CI:
```
  4  .tox/env/lib/python3.10/site-packages/poetry/console/commands/install.py:71 in handle
     return_code = self._installer.run()
  3  .tox/env/lib/python3.10/site-packages/poetry/installation/installer.py:93 in run
     if not self._update and not self._locker.is_locked():
  2  .tox/env/lib/python3.10/site-packages/poetry/packages/locker.py:74 in is_locked
     return "package" in self.lock_data
  1  .tox/env/lib/python3.10/site-packages/poetry/packages/locker.py:63 in lock_data
     self._lock_data = self._get_lock_data()
  RuntimeError
  The lock file is not compatible with the current version of Poetry.
  Upgrade Poetry to be able to read the lock file or, alternatively, regenerate the lock file with the `poetry lock` command.
  at .tox/env/lib/python3.10/site-packages/poetry/packages/locker.py:481 in _get_lock_data
      477│                 "Upgrade Poetry to ensure the lock file is read properly or, alternatively, "
      478│                 "regenerate the lock file with the `poetry lock` command."
      479│             )
      480│         elif not lock_version_allowed:
    → 481│             raise RuntimeError(
      482│                 "The lock file is not compatible with the current version of Poetry.\n"
      483│                 "Upgrade Poetry to be able to read the lock file or, alternatively, "
      484│                 "regenerate the lock file with the `poetry lock` command."
      485│             )
py310: exit 1 (1.68 seconds) /mozci> poetry install -v -E cache pid=112
py310: FAIL ✖ in 34.97 seconds
```

in addition, we have more failures, with credentials while setting up pre-commit:
```
INFO] Initializing environment for https://github.com/pre-commit/mirrors-prettier:prettier@2.7.1.
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
Username for 'https://gitlab.com': 
[taskcluster:error] Could not reclaim task. Error: Task `JptlFY7RS2eVlqdfnBRacg` can't be reclaimed past its deadline of 2023-04-11T15:11:33.785Z.
```

this reference is found here: https://github.com/mozilla/mozci/blob/2138ed0bf2ce245b70143924b1046fc1286c5daf/.pre-commit-config.yaml#L16

so we need to fix poetry>=1.3.0 everywhere, or poetry<=1.2.2, everywhere- this would be dockerfile and tox.  Also we need to adjust the gitlib to be github and use a proper version.

**Comment by jmaher** [comment]
I am unable to create a pull request locally, I think due to:
```
RuntimeError: The Poetry configuration is invalid:
          - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
```

I might be able to figure this out, but it isn't a high priority for me.

**Comment by marco-c** [comment]
I'll try to fix this.

**Comment by marco-c** [comment]
5b5794bb18cb640ad4e68d05d2b2bffa56675a1a fixed the hang.

**Comment by marco-c** [comment]
497252b95f06968575bb59aca4b3290c37d699fc fixed the pre-commit errors.

**Comment by marco-c** [comment]
04d2c8aa7c14a25de682b1121c405feccf9e7213, 60d775d955dd13121a485a23611d936b34a4b205, and c0538c6ec637ed9e16b8b07461a2c698dacad4a9 updated Poetry, Poetry dependences and Cleo.

It is now working locally for me, but it is failing on CI with no error message.

**Comment by marco-c** [comment]
9ae69437875e8d417b75318aecd849bb9152ac4e pins tox to 3.28.0 (the oldest known working) and c6886d720ac82c0196e61450a1ece00d3845a5b9 adds `--no-ansi` to the poetry command.

linting and testing is now working!
Building the docker image is failing, but that's another issue so we can close this.
